/* 2.1 */
DESC PRODUCTS;
DESC SELLERS;

SELECT*FROM SELLERS;
SELECT LIMIT, PRICE, DESCRIPTION, CODE, MANUFACTURER FROM PRODUCTS;

SELECT FULL_NAME, AGE FROM SELLERS WHERE POSITION='Продавец';

SELECT*FROM PRODUCTS;
SELECT DESCRIPTION AS ТОВАР, PRICE AS "ЦЕНА(У.Е.)", PRICE*90 AS "ЦЕНА(РУБ.)" FROM PRODUCTS;

/* 2.2 */
SELECT*FROM PRODUCTS;
SELECT DISTINCT MANUFACTURER FROM PRODUCTS;

SELECT*FROM SELLERS;
SELECT ROWNUM, POSITION, FULL_NAME, EMPLOYMENT_DATE FROM SELLERS WHERE POSITION='Продавец';

/* 3.1 */
SELECT*FROM SELLERS;
SELECT FULL_NAME, RESULT FROM SELLERS WHERE RESULT>20000;      /*3.1.1*/

SELECT *FROM OFFICES;
SELECT CODE, CITY FROM OFFICES WHERE RESULT>PLAN*0.8;          /*3.1.2*/    

SELECT *FROM ORDERS;
SELECT PRODUCT_MANUFACTURER, ORDER_DATE FROM ORDERS WHERE ORDER_DATE BETWEEN ADD_MONTHS('01.09.11',0) AND ADD_MONTHS('01.01.12',0);     /*3.1.4*/

SELECT*FROM SELLERS;
SELECT FULL_NAME, POSITION, PLAN, RESULT FROM SELLERS WHERE POSITION='Продавец' AND RESULT NOT BETWEEN PLAN*0.8 AND PLAN*1.2;        /*3.1.5*/

SELECT*FROM SELLERS;                                                                                                               /*3.1.6*/
SELECT*FROM SELLERS WHERE POSITION='Продавец' AND OFFICE_CODE IN('S01', 'V01', 'V02'); 
SELECT*FROM SELLERS WHERE POSITION='Продавец' AND OFFICE_CODE NOT IN('S01', 'V01', 'V02');                                           
SELECT*FROM SELLERS WHERE POSITION='Продавец' AND OFFICE_CODE IN(SELECT CODE FROM OFFICES WHERE CITY IN ('Сарапул','Воткинск'));
SELECT*FROM SELLERS WHERE POSITION='Продавец' AND OFFICE_CODE IN(SELECT CODE FROM OFFICES WHERE CITY NOT IN ('Сарапул','Воткинск'));

SELECT *FROM ORDERS;
SELECT PRODUCT_MANUFACTURER, ORDER_DATE FROM ORDERS WHERE ORDER_DATE>ADD_MONTHS('01.09.11',0) AND ORDER_DATE<ADD_MONTHS('01.01.12',0);     /*3.1.7 (3.1.4)*/
SELECT* FROM SELLERS WHERE POSITION='Продавец' AND RESULT<PLAN*0.8 OR RESULT>PLAN*1.2;                                                    /*3.1.7 (3.1.5)*/
SELECT* FROM SELLERS WHERE POSITION='Продавец' AND OFFICE_CODE='S01' OR OFFICE_CODE='S02' OR OFFICE_CODE='V01';                          /*3.1.7 (3.1.6)*/
SELECT* FROM SELLERS WHERE POSITION='Продавец' AND OFFICE_CODE!='S01' AND OFFICE_CODE!='S02' AND OFFICE_CODE!='V01';

SELECT*FROM PRODUCTS;
SELECT*FROM PRODUCTS WHERE DESCRIPTION LIKE '%Комплект%' OR DESCRIPTION LIKE '%комплект%';                                            /*3.1.8*/

SELECT*FROM SELLERS;
SELECT*FROM SELLERS WHERE POSITION='Продавец' AND FULL_NAME LIKE '%ич%' OR FULL_NAME LIKE '%ыч%';                          /*3.1.9*/
SELECT * FROM SELLERS WHERE (PLAN = SELLER_ID) OR (AGE = 33);    /*(NULL OR TRUE = TRUE)*/                                       /*3.1.13*/
SELECT * FROM SELLERS WHERE (PLAN = SELLER_ID) AND (AGE = 33);  /*(NULL AND TRUE = NULL)*/                                                                                                                             
SELECT * FROM SELLERS WHERE NOT ((PLAN = SELLER_ID) OR (AGE > 50));  /*(NULL OR FALSE = NULL)*/
SELECT * FROM SELLERS WHERE NOT ((PLAN = SELLER_ID) AND (AGE > 50));  /*(NULL AND FALSE = FALSE)*/



/*3.2*/
SELECT*FROM OFFICES ORDER BY RESULT-PLAN;                                                                                  /*3.2.1*/
SELECT*FROM PRODUCTS ORDER BY CODE DESC, DESCRIPTION;                                                                     /*3.2.2*/
SELECT *FROM (SELECT*FROM SELLERS ORDER BY FULL_NAME)WHERE ROWNUM<6;                                                     /*3.2.3*/


/*4.1*/
SELECT FULL_NAME AS "Фамилия И.О.", POSITION, PLAN*1.15 AS "PLAN NEXT MONTHS" FROM SELLERS WHERE POSITION='Продавец';             /*4.1.1*/
SELECT FULL_NAME, (RESULT-PLAN)*0.07 AS "Премия" FROM (SELECT*FROM SELLERS WHERE RESULT-PLAN>0) ORDER BY OFFICE_CODE;            /*4.1.2*/
SELECT FULL_NAME, POSITION, TO